---
- name: Configure cronjobs
  hosts: aws_server
  tasks:
    - name: Renovation of SSL certificates every 2 months
      cron:
        name: "Renovation of SSL certificates"
        month: "*/2"
        day: "1"
        hour: "0"
        minute: "0"
        job: "certbot renew --nginx; systemctl reload nginx"
        user: root

    - name: Send request to URL every 15 minutes
      cron:
        name: "Send request to URL"
        minute: "*/15"
        job: "curl https://do-discord-bot.onrender.com/"

    - name: Get images every 30 minutes
      cron:
        name: "Get images"
        minute: "*/30"
        job: "curl https://waifuland-api.onrender.com/api/images"

    - name: Restart Docker container every 5 days
      cron:
        name: "Restart Docker container"
        minute: "0"
        hour: "0"
        day: "*/5"
        ## Remember to change the container id
        job: "docker restart <new-id>"
