---
- name: install nginx proxy manager
  hosts: aws_server
  become_user: ubuntu
  become: yes
  tasks:
    - name: Update nginx
      become: yes
      apt: name=nginx state=latest
    
  ## TODO: Add nginx configuration