---
- name: Update system and install packages
  hosts: aws_development
  become_user: root
  become: yes
  tasks:
    - name: Run apt-get update
      become: yes
      apt: update_cache=yes
    
    - name: Run apt-get upgrade
      become: yes
      apt: upgrade=dist

    - name: Install packages
      become: yes
      apt: name={{ item }} state=latest
      with_items:
        - python3-pip
        - git

    - name: Run autoclean
      become: yes
      apt: autoclean=yes
    
    - name: Run clean
      become: yes
      apt: clean=yes
      
    - name: Run autoremove
      become: yes
      apt: autoremove=yes
    
  ## TODO: Rest of the tasks