version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-files
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /mnt/public_files/files:/mnt/public_files/files
    restart: always
